<center><h2>Numpy开始学习</h2></center>

## 创建一维数组

## 创建二维数组
> * 同时获取数组的维数、元素类型、尺寸、大小
> * 对数组进行变形

In [16]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("创建的数组为\n",arr2)
print("数组的维数为:",arr2.ndim)
print("数组的元素类型为:",arr2.dtype)
print("数组的尺寸为:",arr2.shape)
print("数组的元素总数为:",arr2.size)
arr2.shape=4,3
print("变形后的数组为\n",arr2)

创建的数组为
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
数组的维数为: 2
数组的元素类型为: int32
数组的尺寸为: (3, 4)
数组的元素总数为: 12
变形后的数组为
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 使用其他函数创建数组
> * 书P24,25

In [19]:
arr3=np.arange(0,1,0.1)
print("arange创建的数组\n",arr3)
arr4=np.linspace(0,1,12)
print("linspace创建的数组\n",arr4)

arange创建的数组
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
linspace创建的数组
 [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


## 生成随机数
> * 书P27
> * 生成随机数
> * 生成均匀分布的随机数
> * 生成正态分布的随机数
> * 生成有上下界的随机数

In [4]:
import numpy as np
randomNum = np.random.random(10)
print("生成10个随机数:\n",randomNum)

生成10个随机数:
 [0.47171325 0.85623581 0.80800421 0.28646988 0.9776967  0.04052419
 0.36800606 0.28299725 0.09763269 0.87575144]


In [6]:
randomNum02 = np.random.rand(7,5)
print("生成35个(七行五列)均匀分布的随机数:\n",randomNum02)

生成35个(七行五列)均匀分布的随机数:
 [[0.3189248  0.13344771 0.46301869 0.08866697 0.11451368]
 [0.15019758 0.42684885 0.99271342 0.77517259 0.26219895]
 [0.28992545 0.72589095 0.20059862 0.86021227 0.15579992]
 [0.73422444 0.93445219 0.26381202 0.32091088 0.06126675]
 [0.3453675  0.06041858 0.38793452 0.44201503 0.43866942]
 [0.79426721 0.48274587 0.87386716 0.55382084 0.4953978 ]
 [0.98346841 0.13114616 0.94200452 0.54697804 0.03380719]]


In [8]:
randomNum03 = np.random.randn(7,5)
print("生成35个(七行五列)正态分布的随机数:\n",randomNum03)

生成35个(七行五列)正态分布的随机数:
 [[ 0.45687151 -1.86408837 -1.37992074  0.07177512  0.91828115]
 [ 1.78534296 -0.72832636 -0.85025041  0.61492531  0.52364453]
 [-0.61365716  0.50567316 -1.13205556  0.31729738  0.70614898]
 [-1.1918284   1.27038231  0.45910529  1.64491644  0.25897367]
 [ 0.05061616  0.76461907 -1.62023669  0.15920641  2.69412587]
 [-0.51241364 -2.07627751 -3.48565498  0.73788446 -1.67384173]
 [-1.95300192  0.15555911 -0.95766137  1.4009075  -1.24296147]]


In [11]:
randomNum04 = np.random.randint(2,10,size=[2,5])
print("生成不小于2不大于10(左开右闭)的10个(二行五列)随机数:\n",randomNum04)

生成不小于2不大于10(左开右闭)的10个(二行五列)随机数:
 [[3 9 3 6 7]
 [4 4 6 7 3]]


# 矩阵
> 广播机制(书P39)

即不同维数的数组进行运算，可以通过函数进行补充

In [2]:
import numpy as np
arr1=np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr2=np.array([1,2,3,4]).reshape((4,1))
arr1+arr2

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

# Numpy的统计分析
> 书P41读写文件

## 保存数组至文件
> * 单个数组用save方法,文件后缀默认为npy
> * 多个数组用savez方法，文件后缀npz

In [7]:
arr3=np.arange(20).reshape(4,5)
np.save("./output/save_arr01",arr3) # 保存数组
print("保存的数组是:\n",arr3)

保存的数组是:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
np.savez("./output/save_arr02",arr1,arr2) # 保存多个数组
print("保存的数组1:\n",arr1)
print("保存的数组2:\n",arr2)

保存的数组1:
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
保存的数组2:
 [[1]
 [2]
 [3]
 [4]]


## 从文件读取数组

In [13]:
load_data01=np.load("./output/save_arr01.npy") # 读取单个数组
print("读取的数组是:\n",load_data01)

读取的数组是:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
load_data02=np.load("./output/save_arr02.npz") # 读取多个数组
print("读取的数组1是\n",load_data02['arr_0'])
print("读取的数组2是\n",load_data02['arr_1'])

读取的数组1是
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
读取的数组2是
 [[1]
 [2]
 [3]
 [4]]


## 对数组进行文本形式的存与读

In [5]:
arr = np.arange(20).reshape(4, 5)
print('创建的数组为：\n', arr)

# fmt='%d'表示保存为整数
np.savetxt('./output/arr.txt', arr, fmt='%d', delimiter=',')
# 读入的时候也需要指定逗号分隔
loaded_data = np.loadtxt('./output/arr.txt', delimiter=',') 
print('读取的数组为：\n', loaded_data)

创建的数组为：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
读取的数组为：
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


# 简单的统计分析
## 1.排序

In [11]:
# 代码 2-44
np.random.seed(42)  # 设置随机种子
arr = np.random.randint(1, 10, size=20) # 生成随机数组,数字随机1-9,共20个
print('创建的数组为：', arr)

arr.sort()  # 直接排序
print('排序后数组为：', arr)

print("===================")
arr = np.random.randint(1, 10, size=(4,5))  # 生成4行5列的随机数组
print('创建的数组为：\n', arr)

arr.sort(axis=1)  # 沿着横轴排序
print('沿着横轴排序后数组为：\n', arr)

arr.sort(axis=0)  # 沿着纵轴排序
print('沿着纵轴排序后数组为：\n', arr)

创建的数组为： [7 4 8 5 7 3 7 8 5 4 8 8 3 6 5 2 8 6 2 5]
排序后数组为： [2 2 3 3 4 4 5 5 5 5 6 6 7 7 7 8 8 8 8 8]
创建的数组为：
 [[1 6 9 1 3]
 [7 4 9 3 5]
 [3 7 5 9 7]
 [2 4 9 2 9]]
沿着横轴排序后数组为：
 [[1 1 3 6 9]
 [3 4 5 7 9]
 [3 5 7 7 9]
 [2 2 4 9 9]]
沿着纵轴排序后数组为：
 [[1 1 3 6 9]
 [2 2 4 7 9]
 [3 4 5 7 9]
 [3 5 7 9 9]]


## 去除重复
> 通过unique函数

In [14]:
# 代码 2-47
names = np.array(['小明', '小黄', '小花', '小明', 
    '小花', '小兰', '小白'])
print('创建的数组为：', names)
print('去重后的数组为：', np.unique(names))

创建的数组为： ['小明' '小黄' '小花' '小明' '小花' '小兰' '小白']
去重后的数组为： ['小兰' '小明' '小白' '小花' '小黄']


## 常用的统计函数
> 书P47
> * sum求和
> * mean均值
> * max,min最大最小值
> * std标准差
> * var方差

In [18]:
# 代码 2-50
arr = np.arange(20).reshape(4, 5)
print('创建的数组为：\n', arr)
print('数组的和为：', np.sum(arr))  # 计算数组的和
print('数组横轴的和为：', arr.sum(axis=1))  # 沿着横轴计算求和
print('数组纵轴的和为：', arr.sum(axis=0))  # 沿着纵轴计算求和
print('\n数组的均值为：', np.mean(arr))  # 计算数组均值
print('数组横轴的均值为：', arr.mean(axis=1))  # 沿着横轴计算数组均值
print('数组纵轴的均值为：', arr.mean(axis=0))  # 沿着纵轴计算数组均值
print('\n数组的标准差为：', np.std(arr))  # 计算数组标准差
print('\n数组的方差为：', np.var(arr))  # 计算数组方差
print('\n数组的最小值为：', np.min(arr))  # 计算数组最小值
print('数组的最大元素索引为：', np.argmax(arr))  # 返回数组最大元素的索引

创建的数组为：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
数组的和为： 190
数组横轴的和为： [10 35 60 85]
数组纵轴的和为： [30 34 38 42 46]

数组的均值为： 9.5
数组横轴的均值为： [ 2.  7. 12. 17.]
数组纵轴的均值为： [ 7.5  8.5  9.5 10.5 11.5]

数组的标准差为： 5.766281297335398

数组的方差为： 33.25

数组的最小值为： 0
数组的最大元素索引为： 19
